<?php
session_start();
require_once '../includes/db_config.php';
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') { header('Location: ../login.php'); exit; }
$pdo = getDBConnection();
$message = ''; $messageType = '';
if (isset($_GET['delete'])) { $stmt = $pdo->prepare("UPDATE products SET active = 0 WHERE product_id = :id"); $stmt->execute([':id' => (int)$_GET['delete']]); $message = 'Product deleted successfully.'; $messageType = 'success'; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $name = trim($_POST['name'] ?? ''); $categoryId = (int)($_POST['category_id'] ?? 0); $price = (float)($_POST['price'] ?? 0); $salePrice = !empty($_POST['sale_price']) ? (float)$_POST['sale_price'] : null; $description = trim($_POST['description'] ?? ''); $brand = trim($_POST['brand'] ?? 'Glamour Haven'); $stock = (int)($_POST['stock'] ?? 0); $featured = isset($_POST['featured']) ? 1 : 0; $image = trim($_POST['image'] ?? 'lipstick_red.jpg');
    if (isset($_POST['product_id']) && $_POST['product_id'] > 0) { $stmt = $pdo->prepare("UPDATE products SET name=:name, category_id=:cid, price=:price, sale_price=:sp, description=:desc, brand=:brand, stock=:stock, featured=:feat, image=:img WHERE product_id=:pid"); $stmt->execute([':name'=>$name,':cid'=>$categoryId,':price'=>$price,':sp'=>$salePrice,':desc'=>$description,':brand'=>$brand,':stock'=>$stock,':feat'=>$featured,':img'=>$image,':pid'=>(int)$_POST['product_id']]); $message = 'Product updated successfully!'; }
    else { $stmt = $pdo->prepare("INSERT INTO products (name, category_id, price, sale_price, description, brand, stock, featured, image, active) VALUES (:name, :cid, :price, :sp, :desc, :brand, :stock, :feat, :img, 1)"); $stmt->execute([':name'=>$name,':cid'=>$categoryId,':price'=>$price,':sp'=>$salePrice,':desc'=>$description,':brand'=>$brand,':stock'=>$stock,':feat'=>$featured,':img'=>$image]); $message = 'Product added successfully!'; }
    $messageType = 'success';
}
$products = $pdo->query("SELECT p.*, c.name as category_name FROM products p JOIN categories c ON p.category_id = c.category_id WHERE p.active = 1 ORDER BY p.created_at DESC")->fetchAll();
$categories = $pdo->query("SELECT * FROM categories ORDER BY name")->fetchAll();
$editProduct = null;
if (isset($_GET['edit'])) { $stmt = $pdo->prepare("SELECT * FROM products WHERE product_id = :id"); $stmt->execute([':id' => (int)$_GET['edit']]); $editProduct = $stmt->fetch(); }
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Manage Products | Glamour Haven Admin</title><link rel="icon" href="../images/favicon.ico"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Lato:wght@300;400;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="../css/style.css"></head><body>
<nav class="navbar navbar-dark bg-dark px-4"><a class="navbar-brand" href="dashboard.php"><i class="bi bi-gem me-2"></i>Glamour Haven Admin</a><div><a href="../index.php" class="btn btn-outline-light btn-sm me-2"><i class="bi bi-shop"></i> View Store</a><a href="../logout.php" class="btn btn-outline-danger btn-sm"><i class="bi bi-box-arrow-right"></i> Logout</a></div></nav>
<div class="container-fluid"><div class="row">
    <div class="col-md-2 admin-sidebar p-0"><nav class="nav flex-column mt-3"><a class="nav-link" href="dashboard.php"><i class="bi bi-speedometer2"></i> Dashboard</a><a class="nav-link active" href="manage_products.php"><i class="bi bi-box-seam"></i> Products</a><a class="nav-link" href="manage_orders.php"><i class="bi bi-receipt"></i> Orders</a><a class="nav-link" href="manage_users.php"><i class="bi bi-people"></i> Users</a><a class="nav-link" href="manage_categories.php"><i class="bi bi-tags"></i> Categories</a></nav></div>
    <div class="col-md-10 p-4">
        <div class="d-flex justify-content-between align-items-center mb-4"><h2>Manage Products</h2><button class="btn btn-glamour" data-bs-toggle="modal" data-bs-target="#productModal" onclick="resetForm()"><i class="bi bi-plus-circle me-1"></i> Add Product</button></div>
        <?php if ($message): ?><div class="alert alert-<?php echo $messageType; ?> alert-dismissible fade show"><?php echo $message; ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>
        <div class="card border-0 shadow-sm"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Image</th><th>Name</th><th>Category</th><th>Price</th><th>Sale</th><th>Stock</th><th>Featured</th><th>Actions</th></tr></thead><tbody>
        <?php foreach ($products as $p): ?>
        <tr><td><img src="../images/<?php echo htmlspecialchars($p['image']); ?>" width="50" height="50" style="object-fit:cover; border-radius:5px;"></td><td><strong><?php echo htmlspecialchars($p['name']); ?></strong><br><small class="text-muted"><?php echo htmlspecialchars($p['brand']); ?></small></td><td><?php echo htmlspecialchars($p['category_name']); ?></td><td>$<?php echo number_format($p['price'], 2); ?></td><td><?php echo $p['sale_price'] ? '$' . number_format($p['sale_price'], 2) : '-'; ?></td><td><?php if ($p['stock'] < 10): ?><span class="text-danger fw-bold"><?php echo $p['stock']; ?></span><?php else: echo $p['stock']; endif; ?></td><td><?php echo $p['featured'] ? '<i class="bi bi-star-fill" style="color:var(--primary);"></i>' : '-'; ?></td><td><a href="manage_products.php?edit=<?php echo $p['product_id']; ?>" class="btn btn-sm btn-outline-primary me-1"><i class="bi bi-pencil"></i></a><a href="manage_products.php?delete=<?php echo $p['product_id']; ?>" class="btn btn-sm btn-outline-danger confirm-delete"><i class="bi bi-trash"></i></a></td></tr>
        <?php endforeach; ?>
        </tbody></table></div></div></div>
    </div>
</div></div>
<div class="modal fade" id="productModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST"><div class="modal-header"><h5 class="modal-title" id="modalTitle">Add New Product</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="product_id" id="productId" value="0"><div class="row g-3"><div class="col-md-8"><label class="form-label">Product Name *</label><input type="text" class="form-control" name="name" id="prodName" required></div><div class="col-md-4"><label class="form-label">Category *</label><select name="category_id" id="prodCat" class="form-select" required><?php foreach ($categories as $cat): ?><option value="<?php echo $cat['category_id']; ?>"><?php echo htmlspecialchars($cat['name']); ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Price ($) *</label><input type="number" class="form-control" name="price" id="prodPrice" step="0.01" min="0" required></div><div class="col-md-4"><label class="form-label">Sale Price ($)</label><input type="number" class="form-control" name="sale_price" id="prodSale" step="0.01" min="0"></div><div class="col-md-4"><label class="form-label">Stock *</label><input type="number" class="form-control" name="stock" id="prodStock" min="0" required></div><div class="col-md-6"><label class="form-label">Brand</label><input type="text" class="form-control" name="brand" id="prodBrand" value="Glamour Haven"></div><div class="col-md-6"><label class="form-label">Image Filename</label><input type="text" class="form-control" name="image" id="prodImage" value="lipstick_red.jpg"><small class="text-muted">Place image in /images folder</small></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" id="prodDesc" rows="3"></textarea></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="featured" id="prodFeatured"><label class="form-check-label" for="prodFeatured">Featured Product</label></div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-glamour">Save Product</button></div></form></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script src="../js/main.js"></script>
<script>
function resetForm(){document.getElementById('modalTitle').textContent='Add New Product';document.getElementById('productId').value='0';document.getElementById('prodName').value='';document.getElementById('prodPrice').value='';document.getElementById('prodSale').value='';document.getElementById('prodStock').value='';document.getElementById('prodBrand').value='Glamour Haven';document.getElementById('prodImage').value='lipstick_red.jpg';document.getElementById('prodDesc').value='';document.getElementById('prodFeatured').checked=false;}
<?php if ($editProduct): ?>
window.addEventListener('DOMContentLoaded',function(){document.getElementById('modalTitle').textContent='Edit Product';document.getElementById('productId').value='<?php echo $editProduct['product_id']; ?>';document.getElementById('prodName').value='<?php echo addslashes($editProduct['name']); ?>';document.getElementById('prodCat').value='<?php echo $editProduct['category_id']; ?>';document.getElementById('prodPrice').value='<?php echo $editProduct['price']; ?>';document.getElementById('prodSale').value='<?php echo $editProduct['sale_price'] ?? ''; ?>';document.getElementById('prodStock').value='<?php echo $editProduct['stock']; ?>';document.getElementById('prodBrand').value='<?php echo addslashes($editProduct['brand']); ?>';document.getElementById('prodImage').value='<?php echo addslashes($editProduct['image']); ?>';document.getElementById('prodDesc').value=`<?php echo addslashes($editProduct['description']); ?>`;document.getElementById('prodFeatured').checked=<?php echo $editProduct['featured'] ? 'true' : 'false'; ?>;new bootstrap.Modal(document.getElementById('productModal')).show();});
<?php endif; ?>
</script></body></html>
